const matchData = [
    {
      id: 1,
      photos: ["/api/placeholder/240/200"],
      date: "02/03/2009",
      time: "15:00",
      competition: "Serie A",
      homeTeam: "Inter",
      awayTeam: "Reggina", 
      homeResult: 3,
      awayResult: 0,
      win: 1,
      draw: 0,
      lose: 0, 
      scorers: ["Cambiasso", "Ibrahimović", "Ibrahimović"], 
      minGoal: [6, 10, 58], 
      penalty: [0, 1, 0],
      stadiumMates: ["papa", "mamma", "gio"], // + sergio gasco e famiglia?
      comment: "",
      highlights: "https://www.youtube.com/watch?v=sLjb4voLR7g&ab_channel=vitas%E2%81%B8%C2%B9", 
      matchReport: "https://www.transfermarkt.it/inter_reggina-calcio/index/spielbericht/932339"
    },
    {
      id: 2,
      photos: ["/api/placeholder/240/200"],
      date: "13/03/2012",
      time: "20:45",
      competition: "Champions League",
      round: "Ottvani - Ritorno (0-1)",
      homeTeam: "Inter",
      awayTeam: "Marsiglia", 
      homeResult: 2,
      awayResult: 1,
      win: 1,
      draw: 0,
      lose: 0, 
      scorers: ["Milito", "Brandão", "Pazzini"], 
      minGoal: [75, 92, 96], 
      penalty: [0, 0, 1],
      stadiumMates: ["papa"], // + colleghi? Quinterno?
      comment: "",
      highlights: "https://www.youtube.com/watch?v=Ji4EE7hj9M4", 
      matchReport: "https://www.transfermarkt.it/inter_olympique-marsiglia/index/spielbericht/1174231"
    },
    {
      id: 3,
      photos: ["/api/placeholder/240/200"],
      date: "26/02/2015",
      time: "19:00",
      competition: "Europa League",
      round: "Sedicesimi - Ritorno (3-3)",
      homeTeam: "Inter",
      awayTeam: "Celtic", 
      homeResult: 1,
      awayResult: 0,
      win: 1,
      draw: 0,
      lose: 0, 
      scorers: ["Guarín"],
      minGoal: [88], 
      penalty: [0], 
      stadiumMates: ["papa", "matte", "ciro", "mauro", "papa_ivan", "ivan"], // ruffino ?
      comment: "",
      highlights: "https://www.dailymotion.com/video/x2i7qqr", 
      matchReport: "https://www.transfermarkt.it/inter_celtic-glasgow/index/spielbericht/2531142"
    },
    {
      id: 4,
      photos: ["/api/placeholder/240/200"],
      date: "07/04/2016",
      time: "20:45",
      competition: "Coppa Italia Primavera",
      round: "Finale - Andata",
      homeTeam: "Juventus Primavera",
      awayTeam: "Inter Primavera", 
      homeResult: 0,
      awayResult: 1,
      win: 1,
      draw: 0,
      lose: 0, 
      scorers: ["Bonetto"],
      minGoal: [27], 
      penalty: [0],  
      stadiumMates: ["papa", "claudio"], // ico ?
      comment: "",
      highlights: "https://www.youtube.com/watch?v=yBAeiM7y2Lo&ab_channel=Inter", 
      matchReport: "https://www.transfermarkt.it/juventus-primavera_inter-primavera/index/spielbericht/2664053"
    }, 
    {
      id: 5,
      photos: ["/api/placeholder/240/200"],
      date: "18/09/2018",
      time: "18:55",
      competition: "Champions League",
      homeTeam: "Inter",
      awayTeam: "Tottenham", 
      round: "Girone",
      homeResult: 2,
      awayResult: 1,
      win: 1,
      draw: 0,
      lose: 0, 
      scorers: ["Eriksen", "Icardi", "Vecino"], 
      minGoal: [53, 86, 92], 
      penalty: [0, 0, 0], 
      stadiumMates: ["papa", "matte", "pie_ghiglia", "comi"], // genitori pie ?
      comment: "",
      highlights: "https://www.youtube.com/watch?v=5EobacAvDI4&ab_channel=Inter", 
      matchReport: "https://www.transfermarkt.it/inter_tottenham-hotspur/index/spielbericht/3097958"
    }, 
    {
      id: 6,
      photos: ["/api/placeholder/240/200"],
      date: "03/11/2018",
      time: "15:00",
      competition: "Serie A",
      homeTeam: "Inter",
      awayTeam: "Genoa", 
      homeResult: 5,
      awayResult: 0,
      win: 1,
      draw: 0,
      lose: 0, 
      scorers: ["Gagliardini", "Politano", "Gagliardini", "Joao Mário", "Nainggolan"], 
      minGoal: [14, 16, 49, 91, 94], 
      penalty: [0, 0, 0, 0, 0], 
      stadiumMates: ["papa"],
      comment: "",
      highlights: "https://www.youtube.com/watch?v=qrUBOGw58iU&ab_channel=SerieA", 
      matchReport: "https://www.transfermarkt.it/inter_genoa-cfc/index/spielbericht/3081134"
    },  
    {
      id: 7,
      photos: ["/api/placeholder/240/200"],
      date: "26/12/2018",
      time: "20:30",
      competition: "Serie A",
      homeTeam: "Inter",
      awayTeam: "Napoli", 
      homeResult: 1,
      awayResult: 0,
      win: 1,
      draw: 0,
      lose: 0, 
      scorers: ["Lautaro Martínez"], 
      minGoal: [91], 
      penalty: [0], 
      stadiumMates: ["papa"],
      comment: "",
      highlights: "https://www.youtube.com/watch?v=fj_-9HX4t1U&ab_channel=Inter", 
      matchReport: "https://www.transfermarkt.it/spielbericht/index/spielbericht/3081207"
    },
    {
      id: 8,
      photos: ["/api/placeholder/240/200"],
      date: "26/04/2019",
      time: "20:30",
      competition: "Serie A",
      homeTeam: "Inter",
      awayTeam: "Roma", 
      homeResult: 1,
      awayResult: 1,
      win: 0,
      draw: 1,
      lose: 0, 
      scorers: ["El Shaarawy", "Perišić"], 
      minGoal: [14, 61], 
      penalty: [0, 0], 
      stadiumMates: ["papa"],
      comment: "",
      highlights: "https://www.youtube.com/watch?v=5eqgHlLz6sc&ab_channel=SerieA", 
      matchReport: "https://www.transfermarkt.it/inter_as-roma/index/spielbericht/3081357"
    },
    {
      id: 9,
      photos: ["/api/placeholder/240/200"],
      date: "17/09/2019",
      time: "18:55",
      competition: "Champions League",
      round: "Girone",
      homeTeam: "Inter",
      awayTeam: "Slavia Praga", 
      homeResult: 1,
      awayResult: 1,
      win: 0,
      draw: 1,
      lose: 0, 
      scorers: ["Olayinka", "Barella"], 
      minGoal: [63, 92], 
      penalty: [0, 0], 
      stadiumMates: ["papa"],
      comment: "",
      highlights: "https://www.youtube.com/watch?v=dtSPazT8TJ4&ab_channel=Inter", 
      matchReport: "https://www.transfermarkt.com/inter-milan_sk-slavia-prague/index/spielbericht/3252156"
    },
    {
      id: 10,
      photos: ["/api/placeholder/240/200"],
      date: "21/12/2019",
      time: "18:00",
      competition: "Serie A",
      homeTeam: "Inter",
      awayTeam: "Genoa", 
      homeResult: 4,
      awayResult: 0,
      win: 1,
      draw: 0,
      lose: 0, 
      scorers: ["Lakuku", "Gagliardini", "Esposito", "Lukaku"], 
      minGoal: [31, 32, 64, 71], 
      penalty: [0, 0, 1, 0], 
      stadiumMates: ["papa, mamma, gio, bj"],
      comment: "",
      highlights: "https://www.youtube.com/watch?v=cVXLKZVVC0Y&ab_channel=SerieA", 
      matchReport: "https://www.transfermarkt.it/inter_genoa-cfc/index/spielbericht/3229328"
    },
    {
      id: 11,
      photos: ["/api/placeholder/240/200"],
      date: "15/09/2021",
      time: "21:00",
      competition: "Champions League",
      round: "Girone",
      homeTeam: "Inter",
      awayTeam: "Real Madrid", 
      homeResult: 0,
      awayResult: 1,
      win: 0,
      draw: 0,
      lose: 1, 
      scorers: ["Rodrygo"], 
      minGoal: [89], 
      penalty: [0], 
      stadiumMates: ["papa"],
      comment: "",
      highlights: "https://www.youtube.com/watch?v=_Y7kmhi54oE&ab_channel=SkySport", 
      matchReport: "https://www.transfermarkt.it/inter_real-madrid-cf/index/spielbericht/3651044"
    },
    {
      id: 12,
      photos: ["/api/placeholder/240/200"],
      date: "22/12/2021",
      time: "18:30",
      competition: "Serie A",
      homeTeam: "Inter",
      awayTeam: "Torino", 
      homeResult: 1,
      awayResult: 0,
      win: 1,
      draw: 0,
      lose: 0, 
      scorers: ["Dumfries"], 
      minGoal: [30], 
      penalty: [0], 
      stadiumMates: ["papa", "matte"],
      comment: "",
      highlights: "https://www.youtube.com/watch?v=a-7w2iM7U34&ab_channel=SerieA", 
      matchReport: "https://www.transfermarkt.it/inter_torino-fc/index/spielbericht/3614723"
    },
    {
      id: 13,
      photos: ["/api/placeholder/240/200"],
      date: "22/02/2023",
      time: "21:00",
      competition: "Champions League",
      round: "Ottavi - Andata",
      homeTeam: "Inter",
      awayTeam: "Porto", 
      homeResult: 1,
      awayResult: 0,
      win: 1,
      draw: 0,
      lose: 0, 
      scorers: ["Lukaku"], 
      minGoal: [86], 
      penalty: [0], 
      stadiumMates: ["papa"],
      comment: "",
      highlights: "https://www.youtube.com/watch?v=92MeBvZIApA&ab_channel=SkySport", 
      matchReport: "https://www.transfermarkt.it/inter-fc-porto/index/spielbericht/3956698"
    }, 
    //TORINO 0-1 ROMA 08/04/2023 (Dybala) -> matte, albi, barbe
    {
      id: 14,
      photos: ["/api/placeholder/240/200"],
      date: "26/04/2023",
      time: "21:00",
      competition: "Coppa Italia",
      round: "Semifinale - Ritorno (1-1)", 
      homeTeam: "Inter",
      awayTeam: "Juventus", 
      homeResult: 1,
      awayResult: 0,
      win: 1,
      draw: 0,
      lose: 0, 
      scorers: ["Dimarco"], 
      minGoal: [15], 
      penalty: [0], 
      stadiumMates: ["papa"],
      comment: "",
      highlights: "https://www.youtube.com/watch?v=aVn3G1oyKTI&ab_channel=SerieA", 
      matchReport: "https://www.transfermarkt.it/inter_juventus-fc/index/spielbericht/4019303"
    }, 
    {
      id: 14,
      photos: ["/api/placeholder/240/200"],
      date: "03/06/2023",
      time: "18:30",
      competition: "Serie A",
      homeTeam: "Torino",
      awayTeam: "Inter", 
      homeResult: 0,
      awayResult: 1,
      win: 1,
      draw: 0,
      lose: 0, 
      scorers: ["Brozović"], 
      minGoal: [37], 
      penalty: [0], 
      stadiumMates: ["matte", "barbe", "albi"],
      comment: "",
      highlights: "https://www.youtube.com/watch?v=kjkeUcj7p0E&ab_channel=SerieA", 
      matchReport: "https://www.transfermarkt.it/torino-fc_inter/index/spielbericht/3845114"
    }, 
    //GENOA 4-1 ROMA 28/09/2023 (Gudmundsson, Cristante, Retegui, Thorsby, Messias) -> Gio
    {
      id: 15,
      photos: ["/api/placeholder/240/200"],
      date: "21/10/2023",
      time: "18:00",
      competition: "Serie A",
      homeTeam: "Torino",
      awayTeam: "Inter", 
      homeResult: 0,
      awayResult: 3,
      win: 1,
      draw: 0,
      lose: 0, 
      scorers: ["Thuram", "Lautaro Martínez", "Çalhanoğlu"], 
      minGoal: [59, 67, 95], 
      penalty: [0, 0, 1], 
      stadiumMates: ["papi"],
      comment: "",
      highlights: "https://www.youtube.com/watch?v=ek632j78134&ab_channel=SerieA", 
      matchReport: "https://www.transfermarkt.it/spielbericht/index/spielbericht/4103560"
    }, 
    {
      id: 16,
      photos: ["/api/placeholder/240/200"],
      date: "20/02/2024",
      time: "21:00",
      competition: "Champions League",
      round: "Ottavi - Andata", 
      homeTeam: "Inter",
      awayTeam: "Atletico Madrid", 
      homeResult: 1,
      awayResult: 0,
      win: 1,
      draw: 0,
      lose: 0, 
      scorers: ["Arnautovic"], 
      minGoal: [79], 
      penalty: [0], 
      stadiumMates: ["papi"],
      comment: "",
      highlights: "https://www.youtube.com/watch?v=kw38qauItBA&ab_channel=Inter", 
      matchReport: "https://www.transfermarkt.it/inter_atletico-de-madrid/index/spielbericht/4243691"
    }, 
    {
      id: 17,
      photos: ["/api/placeholder/240/200"],
      date: "30/03/2025",
      time: "15:00",
      competition: "Champions League",
      round: "Girone", 
      homeTeam: "Inter",
      awayTeam: "Monaco", 
      homeResult: 3,
      awayResult: 0,
      win: 1,
      draw: 0,
      lose: 0, 
      scorers: ["Lautaro Martínez", "Lautaro Martínez", "Lautaro Martínez"], 
      minGoal: [4, 16, 67], 
      penalty: [0, 0, 0], 
      stadiumMates: ["papi"],
      comment: "",
      highlights: "https://www.youtube.com/watch?v=kw38qauItBA&ab_channel=Inter", 
      matchReport: "https://www.transfermarkt.it/inter_as-monaco/index/spielbericht/4445055"
    },
    {
      id: 18,
      photos: ["/api/placeholder/240/200"],
      date: "29/01/2025",
      time: "21:00",
      competition: "Serie A",
      homeTeam: "Inter",
      awayTeam: "Udinese", 
      homeResult: 2,
      awayResult: 1,
      win: 1,
      draw: 0,
      lose: 0, 
      scorers: ["Arnautovic", "Frattesi", "Solet"], 
      minGoal: [12, 29, 71], 
      penalty: [0, 0, 0], 
      stadiumMates: ["papi"],
      comment: "",
      highlights: "https://www.youtube.com/watch?v=Co9X_aI9RoQ&ab_channel=SkySport", 
      matchReport: "https://www.transfermarkt.it/spielbericht/index/spielbericht/4374216"
    }, 
    {
      id: 19,
      photos: ["/api/placeholder/240/200"],
      date: "16/04/2025",
      time: "21:00",
      competition: "Champions League",
      round: "Quarti Ritorno - (2-1)",
      homeTeam: "Inter",
      awayTeam: "Bayern Monaco", 
      homeResult: 2,
      awayResult: 2,
      win: 0,
      draw: 1,
      lose: 0, 
      scorers: ["Kane", "Lautaro Martínez", "Pavard", "Dier"], 
      minGoal: [52, 58, 61, 76], 
      penalty: [0, 0, 0, 0], 
      stadiumMates: ["papi"],
      comment: "",
      highlights: "https://www.youtube.com/watch?v=xDSH-QnW3xs&ab_channel=SkySport", 
      matchReport: "https://www.transfermarkt.it/spielbericht/index/spielbericht/4547650"
    }
    
];

export default matchData;